/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dani
 */
public class Inicio extends javax.swing.JFrame {

    public class Imagen extends javax.swing.JPanel {

        public Imagen() {
        this.setSize(825, 742); //se selecciona el tamaño del panel
        }

        //Se crea un método cuyo parámetro debe ser un objeto Graphics

        public void paint(Graphics grafico) {
        Dimension height = getSize();

        //Se selecciona la imagen que tenemos en el paquete de la //ruta del programa

        ImageIcon Img = new ImageIcon(getClass().getResource("../images/fondo.png")); 

        //se dibuja la imagen que tenemos en el paquete Images //dentro de un panel

        grafico.drawImage(Img.getImage(), 0, 0, height.width, height.height, null);

        setOpaque(false);
        super.paintComponent(grafico);
        }
    }
    
    static double Total;
    static String fechaRegreso;
    static Double totalNeto = 0.0;
    String marca;
    String modelo;
    String color;
    String transmision;
    float tanque;
    int inventario;
    String estado;
    int cantidad;
    float total;
    float precio;
    String nombreEmpleado;
    String nombreCliente;
    String noSerie;
    Dimension dim;
    static int row;
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        visibilidad();
        this.setLocationRelativeTo(null);
        obtenerNombreEmpleado();
        cmbDiasRenta.addItem(1);
        cmbDiasRenta.addItem(2);
        cmbDiasRenta.addItem(3);
        cmbDiasRenta.addItem(4);
        cmbDiasRenta.addItem(5);
        //setFechaRegreso(Regreso);
        
        Imagen Imagen = new Imagen();
        pnlFondo.add(Imagen);
        pnlFondo.repaint();
               
    }
    public static void obtenerCodigo(String codigo) {
        frm_codigo.setText(codigo);
        frm_codigo.requestFocus();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        pnlFondo = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnCobrar = new javax.swing.JButton();
        total_venta = new javax.swing.JLabel();
        sasdad = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbDiasRenta = new javax.swing.JComboBox();
        lblFechaEntrega = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblNombCliente = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tbpAdmin = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        btnEmp = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        tbpBajas = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        frm_renta = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblNombreEmpleado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        frm_codigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel4.setOpaque(false);

        btnCobrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCobrar.setText("Cobrar");
        btnCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrarActionPerformed(evt);
            }
        });

        total_venta.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        total_venta.setText("$0.00");

        sasdad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sasdad.setText("Total x dia: ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sasdad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(total_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sasdad)
                            .addComponent(total_venta))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel5.setOpaque(false);

        jLabel2.setText("Cliente:");

        jLabel4.setText("Numero de Dias:");

        jLabel3.setText("Rango de Renta:");

        cmbDiasRenta.setBorder(null);
        cmbDiasRenta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDiasRentaItemStateChanged(evt);
            }
        });

        lblFechaEntrega.setText("Fecha entrega:");

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Devolución De Vehiculos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Buscar Cliente");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Registrar Cliente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cmbDiasRenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblFechaEntrega))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblNombCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(cmbDiasRenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFechaEntrega))
                    .addComponent(jButton5))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jPanel2.setOpaque(false);

        btnEmp.setBackground(new java.awt.Color(255, 255, 255));
        btnEmp.setText("Agregar Empleado");
        btnEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Agregar Vehiculo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        tbpAdmin.addTab("Altas", jPanel3);

        jButton2.setText("Borrar Empleados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton6.setText("Borrar Clientes");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Borrar Vehiculos");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tbpBajasLayout = new javax.swing.GroupLayout(tbpBajas);
        tbpBajas.setLayout(tbpBajasLayout);
        tbpBajasLayout.setHorizontalGroup(
            tbpBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tbpBajasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tbpBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tbpBajasLayout.setVerticalGroup(
            tbpBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbpBajasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        tbpAdmin.addTab("Bajas", tbpBajas);

        frm_renta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Marca", "Modelo", "Color", "Transmisión", "Tanque", "Precio", "No. Serie"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        frm_renta.setOpaque(false);
        jScrollPane1.setViewportView(frm_renta);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbpAdmin)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(tbpAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel6.setOpaque(false);

        jLabel6.setText("Empleado:");

        lblNombreEmpleado.setText("Nombre del Empleado");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Busca Vehiculo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        frm_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frm_codigoActionPerformed(evt);
            }
        });
        frm_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                frm_codigoKeyPressed(evt);
            }
        });

        jLabel1.setText("Id Del Vehiculo:");

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Cerrar Sesión");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(frm_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(372, 372, 372))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(lblNombreEmpleado)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frm_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void frm_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frm_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frm_codigoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        FrmClientes clientes = new FrmClientes();
        clientes.setLocationRelativeTo(this);
        clientes.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BuscarVehiculo buscar = new BuscarVehiculo();
        buscar.setLocationRelativeTo(this);
        buscar.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpActionPerformed
        FrmEmpleado empleado = new FrmEmpleado();
        empleado.setLocationRelativeTo(this);
        empleado.setVisible(true);
    }//GEN-LAST:event_btnEmpActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        FrmVehiculos vehiculos = new FrmVehiculos();
        vehiculos.setLocationRelativeTo(this);
        vehiculos.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void frm_codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_frm_codigoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (frm_codigo.getText().equals("")) {

                JOptionPane.showMessageDialog(null, "Introduzca un codigo");

            } else {
                DefaultTableModel venta = (DefaultTableModel) frm_renta.getModel();
                int codigo = Integer.parseInt(frm_codigo.getText());
                
                //cantidad = Integer.parseInt(txtCantidad.getText());
                try {

                    ResultSet prod = sql.Vehiculos.getVehiculos(codigo);
                    if (prod.next()) {
                        marca = prod.getString("MARCA");
                        modelo = prod.getString("MODELO");
                        color = prod.getString("COLOR");
                        /*inventario = prod.getInt("INVENTARIO");*/
                        estado = prod.getString("ESTADO");
                        transmision = prod.getString("TRANSMISION");
                        tanque = prod.getFloat("TANQUE");
                        precio = prod.getFloat("PRECIO_RENTA");
                        noSerie = prod.getString("NO_SERIE");
                        total = /*cantidad **/ precio;

                        /*if (inventario < cantidad) {
                         if (inventario == 0) {
                         JOptionPane.showMessageDialog(null, "Vehiculo agotado");
                         } else {
                         JOptionPane.showMessageDialog(null, "Vehiculos insuficientes");
                         txtCantidad.setText("");
                         txtCantidad.requestFocus();
                         }
                         } else {
                         if (comprobarRepetidos() == false) {
                         inventario = inventario - cantidad;*/
                        venta.addRow(new Object[]{codigo, marca, modelo, color, transmision, tanque, precio, noSerie});
                        /*}*/
                        frm_codigo.setText("");
                        frm_codigo.requestFocus();
                        calcularTotal();

                        /*}
                         }else {
                         JOptionPane.showMessageDialog(this, "El codigo no existe");
                         */                    }
                } catch (SQLException ex) {
                    Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_frm_codigoKeyPressed

    private void btnCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrarActionPerformed
        DefaultTableModel venta = (DefaultTableModel) frm_renta.getModel();
             row = venta.getRowCount();
             int x;
                System.out.println(row);
        if (row < 1) {
            JOptionPane.showMessageDialog(this, "No hay vehiculos seleccionados");
        }else{
         if(lblNombCliente.getText().equals("")){
                JOptionPane.showMessageDialog(this, "No ha seleccionado a un cliente.");
            }else{
             if(row>=2){
                 JOptionPane.showMessageDialog(this, "No puede rentar mas de un carro por factura.");
                 for (x = venta.getRowCount(); x > 0; x--) {
                venta.removeRow(0);
            }
             }else{
             rentar();
             setTotal(calcularTotal());
             }
        } 
        }
        
    }//GEN-LAST:event_btnCobrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        FrmBorrarEmpleados borrarEmpleados = new FrmBorrarEmpleados();
        borrarEmpleados.setVisible(true);
        borrarEmpleados.setLocationRelativeTo(borrarEmpleados);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        FrmBorrarCliente borrarClientes = new FrmBorrarCliente();
        borrarClientes.setVisible(true);
        borrarClientes.setLocationRelativeTo(borrarClientes);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        FrmBorrarVehiculos borrar = new FrmBorrarVehiculos();
        borrar.setVisible(true);
        borrar.setLocationRelativeTo(borrar);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        BuscarCliente borrar = new BuscarCliente();
        borrar.setVisible(true);
        borrar.setLocationRelativeTo(borrar);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DevolucionVehiculo vehiculos = new DevolucionVehiculo();
        vehiculos.setLocationRelativeTo(this);
        vehiculos.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cmbDiasRentaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDiasRentaItemStateChanged
        java.util.Date ahora = new java.util.Date();
        String Regreso = Fechas.sumarFechasDias(ahora, getDiasRenta());
        setFechaRegreso(Regreso);
        mostrarFechaRegreso(Regreso);
        calcularTotal();
    }//GEN-LAST:event_cmbDiasRentaItemStateChanged

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.dispose();
        FrmLogin login = new FrmLogin();
        login.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    public static void VVLV(){
         int x;
        DefaultTableModel venta = (DefaultTableModel) frm_renta.getModel();
        for (x = venta.getRowCount(); x > 0; x--) {
            venta.removeRow(0);
        }
        calcularTotal();
    }
        
    public boolean comprobarRepetidos() {
        DefaultTableModel venta = (DefaultTableModel) frm_renta.getModel();
        int x = 0;
        boolean bandera = false;

        for (x = 0; x < venta.getRowCount(); x++) {
            String tmpCodigo = String.valueOf(venta.getValueAt(x, 0));
            String Chkcodigo = frm_codigo.getText();
            if (Chkcodigo.equals(tmpCodigo)) {
                bandera = true;
                int temp = Integer.parseInt(venta.getValueAt(x, 1).toString());
                cantidad = temp + cantidad;
                float temp2 = Float.parseFloat(venta.getValueAt(x, 8).toString());
                total = cantidad * temp2;
                inventario = inventario - cantidad;
                venta.setValueAt(cantidad, x, 1);
                venta.setValueAt(total, x, 8);
                venta.setValueAt(inventario, x, 7);
            }
        }
        return bandera;
    }

    public static Double calcularTotal() {
        int x;
        
        totalNeto = 0.00;
        DefaultTableModel venta = (DefaultTableModel) frm_renta.getModel();
        //Si la cantidad de renglones es 0 es decir se hizo ninguna renta, mantiene la variable del total en 0.
        if (venta.getRowCount() == 0) {
            totalNeto = 0.00;
            lblNombCliente.setText("");
        } else {
            //En un numero de iteraciones igual a la cantidad de renglones que tiene la tabla.
            //Guarda en una variable temporal de tipo String el texto que contiene la celda del precio. 
            //Despues de combertir este String a numero va almacenando la suma de estos en otra variable.
            for (x = 0; x < venta.getRowCount(); x++) {
                String tmpTotal = String.valueOf(venta.getValueAt(x, 6));
                Double tmpTotal1 = Double.parseDouble(tmpTotal);
                int DiasRenta = getDiasRenta();
                totalNeto = (totalNeto + tmpTotal1) * DiasRenta;
            }
        }
        total_venta.setText(Format.Mxn(totalNeto));
        return totalNeto;
    }

    public void rentar() {
        int x = 0;
        DefaultTableModel renta = (DefaultTableModel) frm_renta.getModel();
        for (x = 0; x < renta.getRowCount(); x++) {
            int Codigo = (int) renta.getValueAt(x, 0);
            
            if (sql.Vehiculos.rentarVehiculo(Codigo)) {
                Cobrar cobrar = new Cobrar();
                cobrar.setLocationRelativeTo(this);
                cobrar.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(this, "Error al tratar de rentar el vehiculo.");
            }
        }
    }

     public static void setTotal(double total){
        Total = total;
    }
    
    public static double getTotal(){
        return Total;
    }

    public void visibilidad() {
        if (sql.Empleado.isAdmin()) {
            tbpAdmin.setEnabled(true);
        } else {
            tbpAdmin.setEnabled(false);
            btnEmp.setEnabled(false);
            jButton4.setEnabled(false);
            jButton2.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
        }
    }

    public static void obtenerNombreCliente(String nombre) {
        lblNombCliente.setText(nombre);
    }
    
    public static void obtenerNombreEmpleado() {
        lblNombreEmpleado.setText(sql.Empleado.getNombreEmpleado());
    }
    
    public static int getDiasRenta(){
        int Dias = (int) cmbDiasRenta.getSelectedItem();
        return Dias;
    }
     
    public static void setFechaRegreso(String fecha){
        fechaRegreso = fecha;
    }
    
    public static String getFechaRegreso() {
        return fechaRegreso;
    }
    
    public static void mostrarFechaRegreso(String fecha)
    {
    lblFechaEntrega.setText("Fecha de entrega: " + fecha);
    }
    
    public static void calcularFechaRegreso()
    {
        java.util.Date ahora = new java.util.Date();
        String Regreso = Fechas.sumarFechasDias(ahora, getDiasRenta());
        setFechaRegreso(Regreso);
        mostrarFechaRegreso(Regreso);
    }
    
    
    
    
//    public static void asignarDiferenciaFechas(){
//        java.util.Date ahora = new java.util.Date();
//        int DiasRenta = Fechas.diferenciasDeFechas2(ahora, dchFechaEntrega.getDate());
//        lblDiasRenta.setText(String.valueOf(DiasRenta));
//    }
    
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCobrar;
    private javax.swing.JButton btnEmp;
    public static javax.swing.JComboBox cmbDiasRenta;
    private static javax.swing.JTextField frm_codigo;
    static javax.swing.JTable frm_renta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    public static javax.swing.JLabel lblFechaEntrega;
    public static javax.swing.JLabel lblNombCliente;
    public static javax.swing.JLabel lblNombreEmpleado;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JLabel sasdad;
    private javax.swing.JTabbedPane tbpAdmin;
    private javax.swing.JPanel tbpBajas;
    static javax.swing.JLabel total_venta;
    // End of variables declaration//GEN-END:variables
}
